web/router.ex
defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  @doc """
  Determines all endpoints for the app
  check the results with mix phoenix.routes
  """
  scope "/", Discuss do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/wha", PageController, :wha

    resources "/topics", TopicController

  end

  scope "/auth", Discuss do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    get "/:provider/signout", AuthController, :signout
  end


  # Other scopes may use custom stacks.
  # scope "/api", Discuss do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Discuss.LayoutView do
  use Discuss.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    <link rel="stylesheet" href="https:/fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <div class="container">

      <nav class="light-blue">
        <div class="nav-wrapper container">
            <%= link "Discussions", to: topic_path(@conn, :index), class: "brand-logo"  %>
            <div class="right">
              <%= if @conn.assigns[:user] do %>
                <li>
                  <%= link "Logout", to: auth_path(@conn,:signout, "github") %>
                  </li>
              <% else %>
                <%= link "Login with Github", to: auth_path(@conn,:request, "github") %>
              <% end %>

            </div>
        </div>


      </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>


</html>